lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, biodatas

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^add-friend/$', add_friend, name='add-friend'),
     url(r'^validate-npm/$', validate_npm, name='validate-npm'),
     url(r'delete-friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete-friend'),
     url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
     url(r'biodata/(?P<friend_id>[0-9]+)/$', biodatas, name='biodatas'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
from lab_1.views import index as index_lab1
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
	url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^$', RedirectView.as_view(url='lab-4/',permanent=True), name='index'),
	url(r'^lab-3/', include(lab_3,namespace='lab-3')),
	url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    added_at = models.DateField(auto_now_add=True)
    alamat = models.CharField(max_length = 400,  default="-")    
    kodepos = models.CharField(max_length=50, default="0")
    kotalahir = models.CharField(max_length=200, default = "-")
    tgllahir = models.CharField(max_length=400, default="-")
    prodi = models.CharField(max_length=100, default="-")

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada

    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    friend_list = Friend.objects.all()

    paginator = Paginator(mahasiswa_list, 10)
    page = request.GET.get('page')

    try :
    	mahasiswa = paginator.page(page)
    except PageNotAnInteger:
    	mahasiswa = paginator.page(1)
    #except EmptyPage:
    #	mahasiswa = paginator.page(paginator.num_pages)

    response = {"mahasiswa_list": mahasiswa, "friend_list": friend_list}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        alamat = request.POST['alamat']
        kodepos = request.POST['kodepos']
        kotalahir = request.POST['kotalahir']
        tgllahir = request.POST ['tgllahir']
        prodi = request.POST['prodi']
        
        if not Friend.objects.filter(npm = npm).exists():
        	friend = Friend(friend_name=name, npm=npm, alamat = alamat, 
        	kodepos = kodepos, kotalahir = kotalahir, tgllahir = tgllahir, prodi = prodi)
        	friend.save()
        data = model_to_dict(friend)
        return HttpResponse(data)
        
def delete_friend(request, friend_id):
    Friend.objects.filter(npm=friend_id).delete()
    return HttpResponseRedirect('/lab-7/')

def biodatas (request, friend_id):
    friend = Friend.objects.filter(npm=friend_id)[0]
    response['friend'] = friend
    html = 'lab_7/biodata.html'
    return render(request, html, response)

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    friend_list = Friend.objects.all()
    data = {
        'is_taken': Friend.objects.filter(npm = npm).exists() #lakukan pengecekan apakah Friend dgn npm tsb sudah ada
        }
    return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

lab_7/templates/lab_7/biodata.html
{% extends "lab_7/layout/base.html" %}
{% block content %}

<html>
<section>
<body style="margin-top:10px">
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
	}
</style>
<h2>About Friend</h2>
<table>
  <tr>
    <th>Nama</th>
    <td>{{friend.friend_name}}</td>
  </tr>
  <tr>
    <th>NPM</th>
    <td>{{friend.npm}}</td>
  </tr>
  <tr>
    <th>Alamat</th>
    <td>{{friend.alamat}}</td>
  </tr>
    <tr>
    <th>Kode Pos</th>
    <td>{{friend.kodepos}}</td>
  </tr>
    <tr>
    <th>Kota Lahir</th>
    <td>{{friend.kotalahir}}</td>
  </tr>
  <tr>
    <th>Tanggal Lahir</th>
    <td>{{friend.tgllahir}}</td>
  </tr>
  <tr>
    <th>Prodi</th>
    <td>{{friend.prodi}}</td>
  </tr>
</table>
</body>
</section>
{% endblock %}

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block javascript %}
    <script>
        $( document ).ready(function () {
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:get-friend-list" %}', //#URL untuk mendapatkan list teman],
                success: function (response) {
                    {% for friend in friend_list %}
                        $("#friend-list").append("<a class='list-group-item clearfix'> {{friend.friend_name}} {{friend.npm}} </a>")
                    {% endfor %}
                },
                error: function(error){
                     alert("OPPS mana nih temannya belum ada")
                }
            });
        });
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}', '{{ mahasiswa.alamat_mhs }}', '{{ mahasiswa.kd_pos_mhs }}', '{{ mahasiswa.kota_lahir }}', '{{ mahasiswa.tgl_lahir }}', '{{ mahasiswa.program.0.nm_org }} ({{ mahasiswa.program.0.nm_prg }})')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}


                    <meta charset="utf-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1">
                        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
                        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

                        <div class="container">
                          <ul class ="pagination">
                            {% if mahasiswa_list.has_previous %}
                              <li><a href ="?page = {{ mahasiswa_list.previous_page_number}}">previous</a></li>
                            {% endif %}
                              Page {{mahasiswa_list.number }} of {{ mahasiswa_list.paginator.num_pages }} 

                            {% if mahasiswa_list.has_next %}
                              <li><a href="?page={{ mahasiswa_list.next_page_number }}">next</a></li>
                            {% endif %}
                          </ul>
                        </div>
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                                <span class="btn btn-xs btn-default" onClick="deleteFriend('{{ friend.npm }}')">Hapus Teman
                        </span>
                                <span class="btn btn-xs btn-default" onClick="biodata('{{ friend.npm }}')">View Teman
                        </span>



                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>

                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>

                    <label for="field_alamat">alamat</label>
                    <input id="field_alamat" type="text" name="name" class="form-control"/>

                    <label for="field_kodepos">kode pos</label>
                    <input id="field_kodepos" type="text" name="name" class="form-control"/>

                    <label for="field_kotalahir">kota lahir</label>
                    <input id="field_kotalahir" type="text" name="name" class="form-control"/>

                    <label for="field_tgl_lahir">tanggal lahir</label>
                    <input id="field_tgl_lahir" type="text" name="name" class="form-control"/>

                    <label for="field_prodi">prodi</label>
                    <input id="field_prodi" type="text" name="name" class="form-control"/>

                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>

    var biodata = function (id) {
        window.open ('biodata/' + id + '/' ,'_self');
    }
    var deleteFriend = function(id) {
        window.open ('delete-friend/' + id + '/', '_self');
    }

    var addFriend = function(nama, npm, alamat, kodepos, kotalahir, tgllahir, prodi) {
        $.ajax({
            method: "POST",
            url: "{% url "lab-7:add-friend" %}",
            data: { name: nama, npm: npm, alamat : alamat, kodepos : kodepos, kotalahir : kotalahir, tgllahir: tgllahir, prodi : prodi},
            success : function (friend) {
                html = '<a class="list-group-item clearfix">' +
                    friend.friend_name +
                    '</a>';
                $("#friend-list").append(html)
               
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    $("#add-friend").on("submit", function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
       alamat =  $("#field_alamat").val()
       kodepos =  $("#field_kodepos").val()
       tgllahir =  $("#field_tgl_lahir").val()
       kotalahir =  $("#field_kotalahir").val()
       prodi =  $("#field_prodi").val()
       addFriend(name, npm, alamat, kodepos, kotalahir, tgllahir,  prodi)
       event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}